{% set name = "emmet-core" %}
{% set version = "0.36.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsproject/emmet/archive/v{{ version }}.tar.gz
  sha256: ffa0c5a973455a33190e50b0b5c93c3d6cb67f1df1573439c5d20370d3ac10e9
  patches:
    - version.patch

build:
  noarch: python
  script: cd emmet-core && {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
    - setuptools-scm >=6,<8
  run:
    - monty >=2021.3,<2023.0
    - pybtex >=0.24
    - pydantic ==1.10.2
    - pymatgen >=2021.3,<2023.0
    - python >=3.8
    - spglib <2.0.0
    - typing-extensions >=3.7,<5.0

test:
  imports:
    - emmet.core
    - emmet.core.feff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Core Emmet Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
