{% set name = "emmet-core" %}
{% set version = "0.83.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-core-{{ version }}.tar.gz
  sha256: 78d8a0943cf62104ee012978a48644dbbe5a1db0470f4f13a3d25b30bed1315d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - pymatgen ==2024.4.13
    - monty >=2024.2.2
    - pydantic >=2.0
    - pydantic-settings >=2.0
    - pydantic-core >=2.0
    - pybtex >=0.24,<1.dev0
    - typing-extensions >=3.7
    - spglib >=2.0.1

test:
  imports:
    - emmet.core
    - emmet.core.feff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Core Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
