{% set name = "emmet-core" %}
{% set version = "0.54.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-core-{{ version }}.tar.gz
  sha256: aa5b1b0349bf68b663c9b05eac4a5b17968de9153391b17a2caff5916bbf79fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
    - setuptools-scm >=6,<8
  run:
    - monty >=2021.3
    - numpy
    - pybtex >=0.24
    - pydantic >=1.10.2
    - pymatgen >=2021.3
    - python >=3.8
    - spglib >=2.0.1
    - typing-extensions >=3.7,<5.0

test:
  imports:
    - emmet.core
    - emmet.core.feff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Core Emmet Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
