{% set name = "emmet-core" %}
{% set version = "0.78.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-core-{{ version }}.tar.gz
  sha256: d8daddbadc6dae2ac0fa4a2c151dbb4ed0d7599445087f6e3908d7d5949434a9
  patches:
    - setup.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools-scm
    - pip
  run:
    - python >=3.9
    - pymatgen >=2023.10.11
    - monty >=2024.2.2
    - pydantic >=2.0
    - pydantic-settings >=2.0
    - pydantic-core >=2.0
    - pybtex >=0.24,<1.dev0
    - typing-extensions >=3.7
    - spglib >=2.0.1

test:
  imports:
    - emmet.core
    - emmet.core.feff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Core Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
