{% set name = "emmet-core" %}
{% set version = "0.39.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/emmet-core-{{ version }}.tar.gz
  sha256: 7a1890492feca64e4ae07ba09646da066c41eaf62a5097df5cdec623a0fb8c7a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
    - setuptools-scm >=6,<8
  run:
    - monty >=2021.3,<2023.0
    - pybtex >=0.24
    - pydantic =1.10.2
    - pymatgen >=2021.3,<2023.0
    - python >=3.8
    - spglib =2.0.2
    - typing-extensions >=3.7,<5.0

test:
  imports:
    - emmet.core
    - emmet.core.feff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Core Emmet Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
