{% set name = "emmet-core" %}
{% set version = "0.38.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/materialsproject/emmet/archive/v{{ version }}.tar.gz
  sha256: fb3127b078897b824ad14698185136f6e757ee773ec0dcb32f681248e70a6803
  patches:
    - version.patch
    - spglib.patch

build:
  noarch: python
  script: cd emmet-core && {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools-scm
    - setuptools-scm >=6,<8
  run:
    - monty >=2021.3,<2023.0
    - pybtex >=0.24
    - pydantic ==1.10.2
    - pymatgen >=2021.3,<2023.0
    - python >=3.8
    - spglib <3.0.0
    - typing-extensions >=3.7,<5.0

test:
  imports:
    - emmet.core
    - emmet.core.feff
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/materialsproject/emmet
  summary: Core Emmet Library
  license: BSD-3-Clause
  license_file:
    - LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
