schema_version: 1

context:
  name: emmet-core
  version: "0.87.2"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/${{ name[0] }}/${{ name }}/${{ name | replace('-', '_') }}-${{ version }}.tar.gz
  sha256: 2a525752401626c537183d35cb3bd1f4a7aaae564f4867e75d06e6be655c0248

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - setuptools-scm
    - pip
  run:
    - inflect
    - pubchempy
    - blake3
    - pymatgen-io-validation >=0.1.1
    - monty >=2024.2.2
    - pybtex >=0.24,<1.dev0
    - pydantic >=2.12
    - pydantic-settings >=2.0
    - pydantic-core >=2.0
    - pymatgen >=2024.6.10
    - python >=${{ python_min }}
    - typing_extensions >=3.7

tests:
  - python:
      imports:
        - emmet.core
        - emmet.core.feff
      pip_check: true
      python_version: ${{ python_min }}

about:
  summary: Core Emmet Library
  license: BSD-3-Clause
  license_file: LICENSE
  homepage: https://github.com/materialsproject/emmet

extra:
  recipe-maintainers:
    - jan-janssen
